// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVX2YeVB2NyZseLIAwDC8jbaa6xzYIUHA',
    appId: '1:1030120334054:web:1368c5caa1ad2cf4a35127',
    messagingSenderId: '1030120334054',
    projectId: 'historyquiz-fde30',
    authDomain: 'historyquiz-fde30.firebaseapp.com',
    storageBucket: 'historyquiz-fde30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPQnIZX0u-Plke0vB4aM4f1FRTMuYYI38',
    appId: '1:1030120334054:android:7fd20e5a1fca58b4a35127',
    messagingSenderId: '1030120334054',
    projectId: 'historyquiz-fde30',
    storageBucket: 'historyquiz-fde30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjscjsL7dGEO3mtPv4zuGeRyS6jYmkVK8',
    appId: '1:1030120334054:ios:e35d44fd70ee3d34a35127',
    messagingSenderId: '1030120334054',
    projectId: 'historyquiz-fde30',
    storageBucket: 'historyquiz-fde30.appspot.com',
    iosClientId:
        '1030120334054-7ghfltf86krvmluk2suib9gm8ho13mrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.histoquiz',
  );
}
